### ISSUE TITLE
Partial text on loading screen

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [drfiemost/Hurrican#17]
When starting a game, there is some text shown below the level loading progress bar. Usually it's just a single letter, somewhat off to the left (the exact position differs from one instance to the next, as if it's the first letter of some center-justified text of varying lengths.) Once in a while instead of a single letter it will be a longer string.

This happens whether I'm loading the tutorial, a new game, or a saved game.

![20211230_091729](https://user-images.githubusercontent.com/92833764/147775286-57a1d3dc-5a3b-48c3-a971-70860c793697.png)

![20211230_091911](https://user-images.githubusercontent.com/92833764/147775324-3d3ec31c-5dc6-4f04-bcbc-5b93d1e892ca.png)

![20211230_092022](https://user-images.githubusercontent.com/92833764/147775348-171e1c2e-81db-4082-97d1-3b68a482ce29.png)

![20211230_091757](https://user-images.githubusercontent.com/92833764/147775390-43ffbf18-ad70-4f34-9c00-a92d765b0efa.png)

**Comment by drfiemost** [comment]
I thought it only happened in debug builds but it's not.
Anyway bisected and found the bad commit: e6f8862
