### ISSUE TITLE
Error trying to build on GNU/Linux SDL2

### ISSUE THREAD

**Issue by vanfanel** [drfiemost/Hurrican#3]
Hi there @drfiemost 

I have just discovered this fork of the fantastic Hurrican, and trying to build it.

However, upon trying to build it I get this on Debian 10 / aarch64:

```

pi@raspberrypi:~/src/Hurrican/Hurrican/b4 $ cmake -DCMAKE_BUILD_TYPE=Release -DRENDERER=GLES3 ..
CMake Error at CMakeLists.txt:485 (find_package):
  By not providing "FindSDL2_image.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "SDL2_image", but CMake did not find one.

  Could not find a package configuration file provided by "SDL2_image" with
  any of the following names:

    SDL2_imageConfig.cmake
    sdl2_image-config.cmake

  Add the installation prefix of "SDL2_image" to CMAKE_PREFIX_PATH or set
  "SDL2_image_DIR" to a directory containing one of the above files.  If
  "SDL2_image" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/pi/src/Hurrican/Hurrican/b4/CMakeFiles/CMakeOutput.log".
```

Any idea on why isn't it finding SDL2_image? It's installed on my system.
I have been using it for years, currently I have built and installed SDL2_image 2.0.5 which is the most recent stable version.

**Comment by drfiemost** [comment]
I guess you're missing the sdl2-cmake-scripts, can you please clone the repository again with the --recurse-submodules option?
I've updated the README accordingly.

**Comment by drfiemost** [comment]
Hope the issue is solved, if not reopen.

**Comment by vanfanel** [comment]
@drfiemost Sorry I didn't answer! Github didn't send me an email on this... Will test ASAP.

**Comment by vanfanel** [comment]
@drfiemost Got it to build! What a fantastic (and conveniently SDL2-compatible) fork of a great game!

Just a little question... HOW can I make it look TV-ish like the screenshot on the main page? That shoot seems so awesome.

PD: Can you recommend similar ports of Amiga-like games like this one? I am always searching for treasures like this!

**Comment by drfiemost** [comment]
@vanfanel That's good news!
You can use the --crt  command line parameter to enable TV simulation.
The avalable options are listed at https://github.com/drfiemost/Hurrican/wiki/Help

Unfortunately I'm not aware of any other game as such :(

**Comment by vanfanel** [comment]
@drfiemost Oh thanks for the clue! Will test and enjoy it immediately! :D

**Comment by vanfanel** [comment]
@drfiemost Oh my! CRT mode looks AWESOME! Is it some kind of shader???
It even works perfect in GLES2 builds!

**Comment by drfiemost** [comment]
@vanfanel yes, a GL shader (https://github.com/drfiemost/Hurrican/blob/master/Hurrican/data/shaders/320/shader_render.frag)

**Comment by vanfanel** [comment]
@drfiemost Oh, beautiful one! Do you know if there's a GLSL version of that shader?
Looks great and seems to be pretty fast, so RetroArch on Raspberry Pi could benefit from it.

**Comment by drfiemost** [comment]
@vanfanel It is GLSL, but it's tailored on Hurrican code. By the way it is mostly based on [this article](https://luka712.github.io/2018/07/21/CRT-effect-Shadertoy-Unity/)
