### ISSUE TITLE
"Could not create EGL window surface" Using KMS/DRM on Odroid-Go Advance (Rk3326)

### ISSUE THREAD

**Issue by shantigilbert** [drfiemost/Hurrican#5]
Thanks for this fork, it works great on the other devices I have tested it, Amlogic S922x and S905x3 using FBDEV. But now I am trying to make this run on the Odroid Go Advance and GameForce Chi which use the RK3326 chipset and KMS/DRM (GBM). 

Compilation is fine but when trying to run the game this is the output: 

```
>--------------------<
| GameInit started   |
>--------------------<

--> SDL/OpenGL init <--
---------------------

Initializing SDL.
SDL initialized.
Failed to create 640x480 window: Could not create EGL window surface

-> Graphics Initialization Failure ...!

-> GameInit error!
```

It seems to be an SDL2 issue, but SDL2 is heavily used in the device so I know that it is working for other games and emulators,  I am not sure why this is happening. Any pointers?

**Comment by drfiemost** [comment]
I'm not really into embedded platforms so just guessing here, can you try running with a different color depth like 16 or 24 using the --depth parameter?

**Comment by shantigilbert** [comment]
Thank you, for some reason I missed that parameter, it works with `--depth 16`
