### ISSUE TITLE
Incorrect dpad/button ID's with gamepad control

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [drfiemost/Hurrican#8]
With gamepad control enabled, the instructions in the tutorial level, that (presumably) *should* read, for example:

"You can move left and right by pressing '**Joypad left**' or '**Joypad right**'. You can crouch by pressing '**Joypad down**'."

...instead render as:

"You can move left and right by pressing '**Joypad left**' or '**Joypad leftJoypad right**'. You can crouch by pressing '**Joypad leftJoypad rightJoypad down**'."

This extends to all the action buttons as well, for example "Press '**button 2**' to fire" becomes "Press '**Joypad leftJoypad rightJoypad downJoypad upJoypad downbutton 1button 2**' to fire." Note: "down-up-down," presumably because in the control setup they're listed "...crouch (down), look up (up), look down (down again), ...".

Issue not present with keyboard control, keys such as "**Right**", "**Down**", "**Left Alt**" render correctly.

**Comment by drfiemost** [comment]
Should be fixed, please check.

**Comment by s1eve-mcdichae1** [comment]
Looks good, thanks!
