### ISSUE TITLE
Tutorial level crashes in gamepad control.

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [drfiemost/Hurrican#9]
Issue not present with keyboard control. With gamepad "`0:Logitech Gamepad F710`" it crashes in the same place every time (as I start to walk down the hill after the destructible wall where the smartbomb is demonstrated.)

I was told to do a gdb backtrace. I think I did that. Does this look like what you need? https://pastebin.com/yabpdLPu

(I was having trouble with the `--args` syntax so I managed this by running it from the data dir with `gdb build/hurrican -ex run` and when that seemed to work, I captured the log by adding `|& tee gdblog.txt`.

If that isn't what you need, I'll need you to explain it like I've never done this before because, well, I haven't.)

**Comment by drfiemost** [comment]
Sorry, I forgot to say that you need to use the `bt` command from the gdb console to get the full backtrace.

**Comment by s1eve-mcdichae1** [comment]
Issue not present on `joystick_pause` branch (though there's another issue, which I will address [there](https://github.com/drfiemost/Hurrican/issues/7#issuecomment-989117302)); I *was* able to complete the tutorial level. I will follow-up if it resurfaces. (Or would it be helpful to recompile the old version and trace the crash anyway?)

**Comment by s1eve-mcdichae1** [comment]
...also fixed in master (446b7a1).

**Comment by drfiemost** [comment]
Excellent, thank you!

**Comment by s1eve-mcdichae1** [comment]
I checked, it *was* still present in 444a4d7 but not in 446b7a1 so it must have been related to #8 somehow.

**Comment by drfiemost** [comment]
Yes, it was writing outside a memory buffer bounds causing problems.
